config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notifications
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  resources :folders do
    resources :sections, only: [:create, :new]
  end
  resources :sections, only: [:destroy, :update] do
    resources :tasks, only: [:index, :create, :new]
    resources :timers, only: [:create, :new]
    resources :webs, only: [:create, :new]
  end
  resources :bookmark_lists, only: [:show, :create, :new, :destroy, :edit, :update] do
    resources :bookmarks, only: [:create, :new]
  end
  resources :bookmarks, only: [:destroy]
  resources :tasks, only: [:destroy, :edit, :update]
  resources :timers, only: [:destroy, :edit, :update]

  root to: "folders#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/folder.rb
class Folder < ApplicationRecord
  belongs_to :user
  has_many :sections, dependent: :destroy
  has_many :tasks, through: :sections, dependent: :destroy
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_one_attached :photo
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy]

  def index
    @folders = Folder.where(user: current_user)
    # Set the current month for the calender if there is a param -> take that value
    # if there is no params take today's date
    @date = params[:start_date].present? ? Date.parse(params["start_date"]) : Date.today
    current_month = @date.beginning_of_month..@date.end_of_month
    # Selects all the tasks for the current month
    @tasks = current_user.tasks.where(date: current_month)
    # if Chatroom.all.count > 0
    #   @chatroom = Chatroom.find(1)
    #   @message = Message.new
    # end
  end

  def show
    # if Chatroom.all.count > 0
    #   @chatroom = Chatroom.find(1)
    #   @message = Message.new
    # end
    @notifications = current_user.notifications
    # @q = Task.ransack(params[:q])
    # @results = @q.result(distinct: true)
    @folders = Folder.where(user: current_user)
    @create = Folder.new
    @edit = Folder.friendly.find(params[:id])

    @sections = Section.where(folder: @folder)
    @section = @sections.first
    @task = Task.new
    @timer = Timer.new
    @web = Web.new
    @tasks = {}
    @timers = {}
    @webs = {}
    @sections.each do |section|
      @tasks[section.id] = Task.where(section: section)
      # @bookmarks[section.id] = Bookmark.where(section: section)
      @timers[section.id] = Timer.where(section: section)
      @webs[section.id] = Web.where(section: section)
    end
  end

  def new
    @folders = Folder.all
    @folder = Folder.new
  end

  def create
    @folder = Folder.new(folder_params)
    @user = current_user
    @folder.user = @user
    if @folder.save
      redirect_to folder_path(@folder)
    else
      render :new
    end
  end

  def edit
    @folder = Folder.friendly.find(params[:id])
  end

  def update
    @folder = Folder.friendly.find(params[:id])
    @folder.update(folder_params)
    redirect_to root_path
  end

  def destroy
    @folder.destroy
    redirect_to root_path
  end

  private

  def set_folder
    @folder = Folder.friendly.find(params[:id])
  end

  def folder_params
    params.require(:folder).permit(:name, :user_id, :photo)
  end
end

app/views/folders/_folder_left_content.html.erb
<div class ="wrapper w-100" >
  <div data-controller="sections">
    <div id="sections-list" data-action="drop->sections#sort">
      <% @sections.order(position: :asc).each do |section| %>
        <div class = "section-item" data-section-type="<%= section.section_type %>" data-section-id="<%= section.id %>">
          <% if section.section_type == "todo" %>
            <div class = "card m-4" >
              <div class="page-header">
                <div data-controller="edit-section" data-edit-section-target="section">
                  <div class = "section" data-edit-section-target="infos" ></div>
                  <h1 class = "container heading" data-action="click->edit-section#displayForm"><%= section.name %></h1>
                  <%= simple_form_for section, html: { class: "d-none mb-5", data: { edit_section_target: "form", action: "submit->edit_section#update" } } do |f| %>
                    <%= f.input :name, label: false %>
                    <%= f.submit class: "card-btn btn btn-outline-dark" %>
                  </div>
                <% end %>
                <div data-controller="tasks">
                  <hr size="10">
                  <div class="tasks-list container" data-tasks-target="list" data-action="drop->tasks#sort">
                    <% @tasks[section.id].sort_by { |task| task.position || 0 }.each do |task| %>
                      <div class="task-bar">
                        <%= render "task_infos", task: task, section: section %>
                      </div>
                    <% end %>
                  </div>
                </div>
                <div id = "task" class = "simple mx-3 my-4">
                  <%= simple_form_for([section, @task], remote: true) do |f| %>
                    <%= f.button :submit, "+", class: "card-btn btn btn-outline-dark" %>
                    <%= f.input :title, placeholder: "Add a task...", label: false %>
                  <% end %>
                </div>
                <span class="bin text-right mr-3 mb-3">
                  <%= link_to ('<i class="fas fa-trash"></i>').html_safe,
                              section_path(section),
                              method: :delete,
                              data: { confirm: "Are you sure?" } %>
                </span>
              </div>
            </div>
          <% end %>
          <% if section.section_type == "timer" %>
            <div class = "card m-4" >
              <h1>Timer</h1>
              <hr size="10">
              <% @timers[section.id].each do |timer| %>
                <span class="text-right">
                </span>
                <span class="text-center mb-2"><strong><%= timer.name %></strong></span>
                <div class="timer">
                  <br>
                  <div class="simple_form">
                    <form name="customForm" id="customForm" class= "timer__controls d-flex mx-5">
                      <button data-time="0" class="timer__button"><i class="fas fa-undo"></i></button>
                      <input type="text" name="minutes" placeholder="Enter Minutes"class="form-control mx-3" id="input">
                      <button type="submit" id= "start"class="timer__button" name="start" value="start"><i class="fas fa-play"></i></button>
                    </form>
                  </div>
                  <div class="display mx-5 mb-5">
                    <h1 class="display__time-left mt-2"></h1>
                    <p class="display__end-time mb-2"></p>
                  </div>
                </div>
              <% end %>
              <% if section.timers.length == 0 %>
                <div id = "timer" class = "my-3 mx-5 text-center">
                  <%= simple_form_for([section, @timer], remote: true) do |f| %>
                    <%= f.input :name, placeholder: "Add a timer...", label: false %>
                    <%= f.button :submit, "Add Timer", class: "card-btn btn" %>
                  <% end %>
                </div>
              <% end %>
              <span class="bin mr-3 mb-3">
                <%= link_to ('<i class="fas fa-trash"></i>').html_safe,
                            section_path(section),
                            method: :delete,
                            data: { confirm: "Are you sure?" } %>
              </span>
            </div>
          <% end %>
          <% if section.section_type == "web" %>
          <div class="web-container m-4 p-4 ">
            <div class = "web-card p-10" >
              <h2>Browser</h2>
              <hr size="10">
              <% @webs[section.id].each do |web| %>
                <span class="text-right">
                </span>
                <div>

  <iframe  class="responsive-iframe" style="background-color:white" type="text/html"  src="<%= web.url %>" frameborder="0"><input type="button" value="Back" onclick="history.back()"></iframe>

</div>
              <% end %>
              <% if section.webs.length == 0 %>
                <div id = "web" class = "my-3 mx-5 text-center">
                  <%= simple_form_for([section, @web], remote: true) do |f| %>
                    <%= f.input :url, input_html: { value: "https://www.google.com/search?igu=1" }, placeholder: "Enter URL - e.g. https://www.google.com/search?igu=1", label: false %>

                    <%= f.button :submit, "Start Browser", class: "card-btn btn" %>
                  <% end %>
                   <br>

                  <p><em>Only iframe enabled urls supported...</em><a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options">More Info</a></p>
                 <br>
                 <p><strong>Resize by dragging bottom right corner of Iframe<strong></p>
                </div>
              <% end %>

            </div>

            <span class="bin mr-3 mb-3">
                <%= link_to ('<i class="fas fa-trash"></i>').html_safe,
                            section_path(section),
                            method: :delete,
                            data: { confirm: "Are you sure?" } %>
              </span>
              </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% # ---------------------------------------------- %>

app/views/folders/_right_sidebar.html.erb
<div class="right-side" :class="{ 'active': rightSide }">
  <div class="account">
    <button class="account-button">
      <svg stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"
          class="css-i6dzq1" viewBox="0 0 24 24">
        <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" />
        <path d="M22 6l-10 7L2 6" />
      </svg>
    </button>
    <button class="account-button">
      <svg stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"
          class="css-i6dzq1" viewBox="0 0 24 24">
        <path d="M18 8A6 6 0 006 8c0 7-3 9-3 9h18s-3-2-3-9M13.73 21a2 2 0 01-3.46 0" />
      </svg>
    </button>
  </div>
  <div class="side-wrapper underline">
    <div class="side-title">Widgets</div>
    <div class="user">
      <%= image_tag("todo.png", :class => "user-img") %>
      <div class="username">Todo List
        <div class="folder-links">
          <% if @folder.id %>
            <%= link_to "Add Todo List", folder_sections_path(@folder, section: { section_type: "todo", name: "My Tasks" }), method: "POST", id: "folder-link", remote: true %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="side-wrapper underline">
    <div class="user">
      <%= image_tag("timer.png", :class => "user-img") %>
      <div class="username"> Timer
        <div class="folder-links">
          <% if @folder.id %>
            <%= link_to "Add Timer", folder_sections_path(@folder, section: { section_type: "timer", name: "Timer" }), method: "POST", id: "folder-link", remote: true %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="side-wrapper underline">
    <div class="user">
      <%= image_tag("web.png", :class => "user-img") %>
      <div class="username"> Web Browser
        <div class="folder-links">
          <% if @folder.id %>
            <%= link_to "Add a Web Browser", folder_sections_path(@folder, section: { section_type: "web", name: "Browser" }), method: "POST", id: "folder-link", remote: true %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

   <div class="notification pl-4">
  <div class="side-title">Notifications</div>
  </div>
  <div class = "notifications">
      <%= render @notifications %>
  </div>
  <div class="overlay" @click="rightSide = false; leftSide = false" :class="{ 'active': rightSide || leftSide }"></div>

</div>

app/views/folders/_task_infos.html.erb
<div data-controller="edit-task" data-edit-task-target="task-item">
  <li class = "task-item" data-edit-task-target="infos" data-task-id="<%= task.id %>" data-task-section-id="<%= section.id %>">
    <i class="fas fa-grip-lines mr-2"></i>
    <% Notification.destroy_all %>
    <% if task.date %>
      <% if task.date <= DateTime.now() %>
        <% CommentNotification.with(task: task).deliver(current_user) %>
      <% end %>
    <% end %>

    <a id = "task<%= task.id %>" data-action="click->edit-task#displayForm"><%= task.title %></a>
    <%= link_to image_tag("remove.png", height: "15", width: "15"),
                task_path(task.id),
                method: :delete,
                data: { confirm: "Are you sure?" } %>
  </li>
  <br>
  <%= simple_form_for(task, html: { class: "d-none mb-5", data: { edit_task_target: "form", action: "submit->edit_task#update" } }) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :date, as: :date %>
    <%= f.input :is_event %>
    <%= f.input :completed, collection: Task.completeds.keys %>
    <%= f.button :submit, "Update Task", class: "card-btn btn" %>
  </div>
<% end %>

app/views/folders/index.html.erb
<div id="myDIVleft">
<%= render 'shared/sidebar', folder: @create, boookmark: @bookmark%>
</div>

<div class="folder-left">
<button class="collapse-button btn btn-primary" id="clickmeindexleft"><i class="fas fa-grip-lines mr-2"></i></button>
<div class="calender-container mr-5 ml-5">

  <%# Simple Calender gem uses start_date and end_date, as their default date params,
  to use custom field name say date use 'attribute: :date', 'date' is the field name in your model%>
  <div class="d-flex align-items-end justify-content-end">
    <label class="switch">
      <% if params[:week] == "true" %>
        <input type="checkbox" name="calender" checked id="toggle">
      <% else %>
        <input type="checkbox" name="calender" id="toggle">
      <% end %>
      <span class="slider round"></span>
    </label>
  </div>

  <div class="monthly" style="<%= params[:week] == "true" ? 'display: none' : '' %>">
    <%# Monthly View ---------------------------------------------------%>
    <%= month_calendar(events: @tasks, attribute: :date) do |date, tasks| %>
      <%# To display just the day use "date.day", if you would like the whole date use "date" %>
      <%= date.day %>
      <%# Iterate through all the tasks for the month and show the tasks with the relavant date %>
      <% tasks.each do |task| %>
        <div class="meeting">
          <p class="m-0"><%=link_to "#{task.title}", edit_task_path(task) %></p>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="weekly" style="<%= params[:week] == "true" ? '' : 'display: none' %>">

    <%# Weekly View ---------------------------------------------------%>
    <%= week_calendar(events: @tasks, attribute: :date) do |date, tasks| %>
      <%= date.day %>
      <% tasks.each do |task| %>
        <div class="meeting">
          <p class="m-0"><%=link_to "#{task.title}", edit_task_path(task) %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
</div>

app/views/folders/new.html.erb
<div id = "folder" class = "card">
  <%= simple_form_for (@folder) do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/folders/show.html.erb
<div id="myDIVleft" data-reflex-permanent>
  <%= render "shared/sidebar", folder: @create %>
</div>
<div class="folder-wrapper d-flex">
<% if !@folder.photo.key.nil? %>
   <div class="folder-left" style="background-image: url('<%= cl_image_path @folder.photo.key, crop: :fill %>')" style = "background-size: cover">
<% else %>
    <div class="folder-left" style="background-image: url('<%= asset_path "wall.jpg", crop: :fill %>')" style = "background-size: cover">
<% end %>
  <div class="d-flex justify-content-between" id = "item">
  <button class="collapse-button btn btn-primary" id="clickmeleft"><i class="fas fa-grip-lines mr-2"></i></button>
  <button class="collapse-button btn btn-primary" id="clickmecenter"><i class="fas fa-grip-lines mr-2"></i></button>
  <button class="collapse-button btn btn-primary" id="clickmeright"><i class="fas fa-grip-lines mr-2"></i></button>
</div>
    <%= render "folder_left_content", folder: @folder %>
  </div>
  <div id="myDIVright" data-reflex-permanent>
    <div class="folder-right h-100">
      <%= render "right_sidebar", folder: @folder %>
    </div>
  </div>
</div>