config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notifications
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  resources :folders do
    resources :sections, only: [:create, :new]
  end
  resources :sections, only: [:destroy, :update] do
    resources :tasks, only: [:index, :create, :new]
    resources :timers, only: [:create, :new]
    resources :webs, only: [:create, :new]
  end
  resources :bookmark_lists, only: [:show, :create, :new, :destroy, :edit, :update] do
    resources :bookmarks, only: [:create, :new]
  end
  resources :bookmarks, only: [:destroy]
  resources :tasks, only: [:destroy, :edit, :update]
  resources :timers, only: [:destroy, :edit, :update]

  root to: "folders#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :folder
  has_one :user, through: :folder
  has_many :tasks, dependent: :destroy
  has_many :timers, dependent: :destroy
  has_many :webs, dependent: :destroy
  enum section_type: %i[todo bookmark timer web]
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:update, :destroy]

  def new
    @folder = Folder.find(params[:folder_id])
    @section = Section.new(section_params)
  end

  def create
    @folder = Folder.friendly.find(params[:folder_id])
    @section = Section.new(section_params)
    @section.folder = @folder
    if @section.save
      redirect_back fallback_location: root_path
    else
      render :new
    end
  end

  def update
    @section = Section.find(params[:id])
    @folder = Folder.find(@section.folder_id)
    @section.update(section_params)
    if @section.save
      redirect_back fallback_location: root_path
    else
      render :new
    end
  end

  def destroy
    @folder = Folder.find(@section.folder_id)
    @section.destroy
    redirect_back fallback_location: root_path
  end

  private

  def set_section
    @section = Section.find(params[:id])
  end

  def section_params
    params.require(:section).permit(:section_type, :position, :visible, :name)
  end
end

app/views/sections/_section.html.erb
<% if section.section_type == "todo" %>
  <div class = "todo-container bg-main text-main">
    <div class="page-header">
      <h1>My Tasks</h1>
      <%= image_tag("bar.png") %>
      <div class = "todo-card">
        <ul class = "hide">
          <% @tasks[section.id].each do |task| %>
            <li>
              <% if task.completed == "completed" %>
                <a class = "add" href="<%=  %>"><%= image_tag("checked.png", height: "15", width: "15") %></a>
              <% else %>
                <a class = "add" href="<%=  %>"><%= image_tag("empty.png", height: "15", width: "15") %></a>
              <% end %>
              <%= "#{task.title} - " %>
              <%= link_to "Delete",
                          task_path(task.id),
                          method: :delete,
                          data: { confirm: "Are you sure?" } %></p>
            <% if task.completed == "completed" %>
            <% end %>
          </li>
        <% end %>
      </ul>
      <a class = "add" href="<%= new_section_task_path(section) %>"><%= image_tag("add.png") %></a>
    </div>
    <%= link_to "Delete This Section",
                  section_path(section),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></p>
</div>
</div>
<% end %>
<% if section.section_type == "bookmark" %>
  <div class = "card">
    <h1><%= section.section_type %></h1>
    <% @bookmarks[section.id].each do |bookmark| %>
      <h3><%= bookmark.name %></h3>
      <p><%= bookmark.url %></p>
      <%= link_to "Delete",
                      bookmark_path(bookmark.id),
                      method: :delete,
                      data: { confirm: "Are you sure?" } %></p>
    <br>
  <% end %>
  <p><%= link_to "Add a bookmark", new_section_bookmark_path(section) %><br>
    <%= link_to "Delete This Section",
                    section_path(section),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %></p>
</div>
<% end %>
<% if section.section_type == "timer" %>
  <%= render 'timers/widget', section: section, timers: @timers %>
<% end %>

app/views/sections/new.html.erb
<div id = "section" class = "card">
  <%= simple_form_for [@folder, @sectio] do |f| %>
    <%= f.input :position %>
    <%= f.input :visible %>
    <%= f.input :section_type, collection: Section.section_types.keys %>
    <%= f.submit %>
  <% end %>
</div>