config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notifications
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  resources :folders do
    resources :sections, only: [:create, :new]
  end
  resources :sections, only: [:destroy, :update] do
    resources :tasks, only: [:index, :create, :new]
    resources :timers, only: [:create, :new]
    resources :webs, only: [:create, :new]
  end
  resources :bookmark_lists, only: [:show, :create, :new, :destroy, :edit, :update] do
    resources :bookmarks, only: [:create, :new]
  end
  resources :bookmarks, only: [:destroy]
  resources :tasks, only: [:destroy, :edit, :update]
  resources :timers, only: [:destroy, :edit, :update]

  root to: "folders#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/timer.rb
class Timer < ApplicationRecord
  belongs_to :section
end

app/controllers/timers_controller.rb
class TimersController < ApplicationController
  def new
    @section = Section.find(params[:section_id])
    @timer = Timer.new
  end

  def create
    @section = Section.find(params[:section_id])
    @folder = Folder.find(@section.folder_id)
    @timer = Timer.new(timer_params)
    @timer.section = @section
    if @timer.save
      redirect_to folder_path(@folder)
    else
      render :new
    end
  end

  def destroy
    @timer = Timer.find(params[:id])
    @section = Section.find(@timer.section_id)
    @folder = Folder.find(@section.folder_id)
    @timer.destroy
    redirect_back fallback_location: root_path
    # redirect_to @folder
  end

  private

  def timer_params
    params.require(:timer).permit(:name)
  end
end

app/views/timers/_widget.html.erb
<div class = "card" >
  <h1><%= section.section_type %></h1>
  <% timers[section.id].each do |timer| %>
    <h3><%= timer.name %></h3>
    <%= link_to "Delete",
                        timer_path(timer.id),
                        method: :delete,
                        data: { confirm: "Are you sure?" } %></p>
  <br>
<% end %>
<p><%= link_to "Add a timer", new_section_timer_path(section) %><br>
  <%= link_to "Delete This Section",
                      section_path(section),
                      method: :delete,
                      data: { confirm: "Are you sure?" } %></p>
</div>

app/views/timers/new.html.erb
<div id = "timer" class = "card">
  <%= simple_form_for [@section, @timer] do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>
</div>